"""Define DSP signal graphs as Pydantic models, compile to C++, and optimize.

Provides 34 node types (arithmetic, filters, oscillators, delays, buffers,
state/timing), graph validation, topological sort, Graphviz visualization,
and a multi-pass optimizing compiler targeting standalone C++. Optional
gen-dsp integration generates adapter code for 10+ audio plugin platforms.
"""

from dsp_graph.compile import compile_graph, compile_graph_to_file
from dsp_graph.gen_dsp_adapter import (
    compile_for_gen_dsp,
    generate_adapter_cpp,
    generate_manifest,
)
from dsp_graph.models import (
    SVF,
    Accum,
    Allpass,
    AudioInput,
    AudioOutput,
    BinOp,
    Biquad,
    Buffer,
    BufRead,
    BufSize,
    BufWrite,
    Change,
    Clamp,
    Compare,
    Constant,
    Counter,
    DCBlock,
    DelayLine,
    DelayRead,
    DelayWrite,
    Delta,
    Fold,
    Graph,
    History,
    Latch,
    Mix,
    Node,
    Noise,
    OnePole,
    Param,
    Phasor,
    PulseOsc,
    Ref,
    SampleHold,
    SawOsc,
    Select,
    SinOsc,
    TriOsc,
    UnaryOp,
    Wrap,
)
from dsp_graph.optimize import constant_fold, eliminate_cse, eliminate_dead_nodes, optimize_graph
from dsp_graph.toposort import toposort
from dsp_graph.validate import validate_graph
from dsp_graph.visualize import graph_to_dot, graph_to_dot_file

__version__ = "0.1.5"

__all__ = [
    "Accum",
    "Allpass",
    "AudioInput",
    "AudioOutput",
    "BinOp",
    "Biquad",
    "BufRead",
    "BufSize",
    "BufWrite",
    "Buffer",
    "Change",
    "Clamp",
    "Compare",
    "Constant",
    "Counter",
    "DCBlock",
    "DelayLine",
    "DelayRead",
    "DelayWrite",
    "Delta",
    "Fold",
    "Graph",
    "History",
    "Latch",
    "Mix",
    "Node",
    "Noise",
    "OnePole",
    "Param",
    "Phasor",
    "PulseOsc",
    "Ref",
    "SVF",
    "SampleHold",
    "SawOsc",
    "Select",
    "SinOsc",
    "TriOsc",
    "UnaryOp",
    "Wrap",
    "compile_for_gen_dsp",
    "compile_graph",
    "compile_graph_to_file",
    "constant_fold",
    "eliminate_cse",
    "eliminate_dead_nodes",
    "generate_adapter_cpp",
    "generate_manifest",
    "graph_to_dot",
    "graph_to_dot_file",
    "optimize_graph",
    "toposort",
    "validate_graph",
]
